sudo: required
dist: trusty
group: deprecated-2017Q4

language: ruby

services:
  - docker

before_install:
  - docker pull najlabioinfo/shinydocker

script:
  - docker run --name protaascan -d -p 8787:8787 -e USER='rstudio' -e PASSWORD='rstudio' najlabioinfo/shinydocker:latest
  - bundle exec rake test
